### ISSUE TITLE
后端在哪？

### ISSUE THREAD

**Issue by AngQin104** [lblblong/copy_wechat#34]

**Comment by lblblong** [comment]
没有后端，只是UI上的一个模仿

**Comment by AngQin104** [comment]
> 没有后端，只是UI上的一个模仿

那打包安装软件后页面是空白的啊

**Comment by lblblong** [comment]
下载我之前打包的：https://github.com/lblblong/copy_wechat/releases/tag/0.0.1
因为这个项目是我好久之前写的，不太清楚现在打包有没有bug

**Comment by AngQin104** [comment]
> 下载我之前打包的：https://github.com/lblblong/copy_wechat/releases/tag/0.0.1 因为这个项目是我好久之前写的，不太清楚现在打包有没有bug

好的，谢谢，我试试
